---
- name: Ace Web Server
  hosts: acewebservers
  become: true
  gather_facts: no
  pre_tasks:
    # - include_vars:
    #     file: secrets.yml
    - name: Install Python, if needed
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get -y install python)
      register: output
      changed_when: output.stdout != ""
    - name: Gathering Facts
      setup:
  roles:
    - commonTools
    - playground # install ace app code, apply settings needed to nginx, etc
